# Generated by Django 4.1 on 2023-04-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_img_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.CharField(default='http://google.com', max_length=1020),
            preserve_default=False,
        ),
    ]
