# Generated by Django 4.2 on 2023-04-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_rename_course_education_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(default=1991, max_length=500),
            preserve_default=False,
        ),
    ]
