# Generated by Django 4.2 on 2023-04-11 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_education_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.CharField(default='South African Red Cross Society', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='endDate',
            field=models.DateField(default=datetime.date(2007, 9, 27)),
        ),
        migrations.AlterField(
            model_name='education',
            name='startDate',
            field=models.DateField(default=datetime.date(2001, 9, 7)),
        ),
    ]
