# Generated by Django 4.2 on 2023-04-11 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_experience_organization_alter_education_enddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='date',
        ),
        migrations.AddField(
            model_name='experience',
            name='endDate',
            field=models.DateField(default=datetime.date(2007, 9, 27)),
        ),
        migrations.AddField(
            model_name='experience',
            name='startDate',
            field=models.DateField(default=datetime.date(2001, 9, 7)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(default='Remote', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='organization',
            field=models.CharField(default='SARCS', max_length=256),
        ),
    ]
